services:
  load_manager:
    build:
      context: ./load_manager
      args:
        LOAD_MANAGER_PORT: 3000
    container_name: load_manager
    ports:
      - "3000:3000"
    env_file:
      - ./load_manager/.env
    restart: always
  p_solicitante:
    build:
      context: ./p_solicitante
    env_file:
      - ./p_solicitante/.env
    profiles: ["manual"]
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/seed:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: