services:
  load_manager:
    build:
      context: ./load_manager
    env_file:
      - ./load_manager/.env
    command: ["-v"]
    ports:
      - 3000:3000
    profiles: ["load_manager"]
  p_solicitante:
    build:
      context: ./p_solicitante
    env_file:
      - ./p_solicitante/.env
    profiles: ["p_solicitante"]
  actor-renew:
    build:
      context: ./actores-ts
    env_file:
      - ./actores-ts/.env
    command: ["-t", "renew"]
    profiles: ["actores"]
  actor-reserve:
    build:
      context: ./actores-ts
    env_file:
      - ./actores-ts/.env
    command: ["-t", "reserve"]
    ports:
      - 3002:3002
    profiles: ["actores"]
  actor-return:
    build:
      context: ./actores-ts
    env_file:
      - ./actores-ts/.env
    command: ["-t", "return"]
    profiles: ["actores"]
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/seed:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles: ["database"]

volumes:
  db_data:
